name: RoboTwin

dataset_instantiate_config:
  _target_: lift3d.dataset.RoboTwinDataset

evaluator_instantiate_config:
  _target_: lift3d.envs.RoboTwinEvaluator
  # image_h: ${image_h}
  # image_w: ${image_w}
  # camera_name: ${camera_name}
  use_point_crop: True
  num_points: 1024
  # point_cloud_camera_names: 
  #   - ${camera_name}

loss_func:
  _target_: torch.nn.functional.mse_loss

